services:
  postgres-master:
    image: postgres:15
    container_name: postgres-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
      PGPASSWORD: password
    volumes:
      - ./data/master-data:/var/lib/postgresql/data
      - ./master/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - postgres-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  postgres-slave:
    image: postgres:15
    container_name: postgres-slave
    depends_on:
      - postgres-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
      PGPASSWORD: password
    volumes:
      - ./data/slave-data:/var/lib/postgresql/data
      - ./slave/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - postgres-network
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

networks:
  postgres-network:
    driver: bridge
