services:
  postgres-master:
    image: postgres:15
    container_name: postgres-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
      PGPASSWORD: password
    volumes:
      - ./data/master-data:/var/lib/postgresql/data
      - ./master/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - postgres-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  postgres-slave:
    image: postgres:15
    container_name: postgres-slave
    depends_on:
      - postgres-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
      PGPASSWORD: password
    volumes:
      - ./data/slave-data:/var/lib/postgresql/data
      - ./slave/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - postgres-network
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
    entrypoint:
      - bash
      - -c
      - |
        # Ensure the data directory is empty before running pg_basebackup
        if [ "$(ls -A /var/lib/postgresql/data)" ]; then
          echo "Data directory is not empty. Cleaning up..."
          rm -rf /var/lib/postgresql/data/*
        fi
        
        # Wait for master to be ready
        until pg_isready -h postgres-master -U postgres; do
          sleep 1;
        done
        
        # Copy the initial database backup from master
        pg_basebackup -h postgres-master -U postgres -D /var/lib/postgresql/data -Fp -Xs -P -R
        
        # Start PostgreSQL
        exec docker-entrypoint.sh postgres

networks:
  postgres-network:
    driver: bridge
